### ISSUE TITLE
Backspace deletes a whole word 

### ISSUE THREAD

**Issue by wesleyParriott** [tulir/mauview#2]
In inputfield.go when Key.Backspace is pressed field.removePreviousWord is fired. Normally when pressing the backspace the previous character is removed. My suggestion is to fire field.removePreviousCharacter when pressing Key.Backspace

**Comment by KhaaL** [comment]
Was this issue resolved? I belive I'm experiencing it gomuks, pressing backspace deletes previous word instead of previous character. This happens in both windows terminal and tabby. Exiting gomuks and using backspace in the same session results in normal behaviour, i.e. it deletes one character at a time. 

Potential relevant bug: https://github.com/tulir/gomuks/issues/322 (although its description is not very fleshed out).

Addenum: this could be caused / affected by the flag Backspace1RemovesWord  / Backspace2RemovesWord flags during compilation, see https://github.com/tulir/gomuks/blob/master/config/config.go#L116-L117
